# Generated by Django 5.0.2 on 2024-06-13 20:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_sistema',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
