# Generated by Django 5.0.2 on 2024-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
