# Generated by Django 5.0.2 on 2024-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('convenios', models.ManyToManyField(blank=True, to='convenios.convenio')),
            ],
        ),
    ]
