# Generated by Django 5.0.2 on 2024-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
