# Generated by Django 5.0.2 on 2024-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_alter_profissional_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
