# Generated by Django 5.0.2 on 2024-03-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('termo_consentimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='pacientes.paciente')),
                ('termo_consentimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_pacientes', to='termo_consentimento.termoconsentimento')),
            ],
        ),
    ]
