# Generated by Django 5.0.2 on 2024-03-31 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo_consentimento', '0002_consentimentopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimentopaciente',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
