# Generated by Django 5.0.2 on 2024-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termo_consentimento', '0003_consentimentopaciente_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoconsentimento',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
