# Generated by Django 5.0.2 on 2024-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atestados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestadopaciente',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
