# Generated by Django 5.0.2 on 2024-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
