# Generated by Django 5.0.2 on 2024-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
