# Generated by Django 5.0.2 on 2024-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
