# Generated by Django 5.0.2 on 2024-03-31 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.BooleanField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('anamnese', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anamnese.anamnese')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
        ),
    ]
