# Generated by Django 5.0.2 on 2024-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0002_anamnesepaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesepaciente',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
