# Generated by Django 5.0.2 on 2024-06-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_anamnesepaciente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesepaciente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
