# Generated by Django 5.0.2 on 2024-03-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.convenio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional')),
            ],
        ),
    ]
