# Generated by Django 5.0.2 on 2024-04-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('produtos', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Cliente')),
                ('descricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricao_receita', to='produtos.produto', verbose_name='Descrição')),
            ],
        ),
    ]
