# Generated by Django 5.0.2 on 2024-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='usuario',
            field=models.CharField(blank=True, max_length=15, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.CharField(blank=True, max_length=15, verbose_name='Usuário'),
        ),
    ]
