# Generated by Django 5.0.2 on 2024-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosconsultorio',
            name='usuario',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
